Select Name from Employee
where salary > (select avg(salary) from employee);


SELECT * FROM EMPLOYEE
WHERE AGE < (
	SELECT MAX(AGE) FROM EMPLOYEE
	WHERE DEPTID = (
		SELECT DEPTID FROM DEPARTMENT 
		WHERE DEPTNAME = 'HR')
	)/2;



SELECT * FROM EMPLOYEE
WHERE SALARY > (
	SELECT MIN(SALARY) FROM EMPLOYEE
	WHERE DEPTID = (
		SELECT DEPTID FROM DEPARTMENT 
		WHERE DEPTNAME = 'Finance')
);


SELECT * FROM EMPLOYEE
WHERE SALARY < (
	SELECT AVG(SALARY) FROM EMPLOYEE
	WHERE DEPTID = (
		SELECT DEPTID FROM DEPARTMENT 
		WHERE DEPTNAME = 'HR')
);


SELECT * FROM EMPLOYEE
WHERE SALARY > 1.5*(
	SELECT AVG(SALARY) FROM EMPLOYEE
);


SELECT * FROM EMPLOYEE
WHERE AGE > (
	SELECT MIN(AGE) FROM EMPLOYEE
	WHERE DEPTID = (
		SELECT DEPTID FROM DEPARTMENT 
		WHERE DEPTNAME = 'IT')
);


SELECT * FROM EMPLOYEE
WHERE SALARY = (
	SELECT AVG(SALARY) FROM EMPLOYEE
	WHERE DEPTID = (
		SELECT DEPTID FROM DEPARTMENT 
		WHERE DEPTNAME = 'HR')
);